---
is_debug: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 8443

database:
  host: "localhost"
  port: 5432
  dbname: "postgres"
  sslmode: "disable"

tls:
  cert_file: "cert.pem"
  key_file: "key.pem"
